//TODO copyright header

// This file was automatically generated by informer-gen

package internalversion

import (
	internalinterfaces "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/client/informers_generated/internalversion/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// DirectorBinds returns a DirectorBindInformer.
	DirectorBinds() DirectorBindInformer
	// DockerBinds returns a DockerBindInformer.
	DockerBinds() DockerBindInformer
	// Virtualhostbinds returns a VirtualhostbindInformer.
	Virtualhostbinds() VirtualhostbindInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// DirectorBinds returns a DirectorBindInformer.
func (v *version) DirectorBinds() DirectorBindInformer {
	return &directorBindInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DockerBinds returns a DockerBindInformer.
func (v *version) DockerBinds() DockerBindInformer {
	return &dockerBindInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Virtualhostbinds returns a VirtualhostbindInformer.
func (v *version) Virtualhostbinds() VirtualhostbindInformer {
	return &virtualhostbindInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
