//TODO copyright header

// This file was automatically generated by informer-gen

package internalversion

import (
	bind "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/apis/bind"
	internalclientset "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/client/clientset_generated/internalclientset"
	internalinterfaces "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/client/informers_generated/internalversion/internalinterfaces"
	internalversion "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/client/listers_generated/bind/internalversion"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// VirtualhostbindInformer provides access to a shared informer and lister for
// Virtualhostbinds.
type VirtualhostbindInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.VirtualhostbindLister
}

type virtualhostbindInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVirtualhostbindInformer constructs a new informer for Virtualhostbind type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVirtualhostbindInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVirtualhostbindInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVirtualhostbindInformer constructs a new informer for Virtualhostbind type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVirtualhostbindInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Bind().Virtualhostbinds(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Bind().Virtualhostbinds(namespace).Watch(options)
			},
		},
		&bind.Virtualhostbind{},
		resyncPeriod,
		indexers,
	)
}

func (f *virtualhostbindInformer) defaultInformer(client internalclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVirtualhostbindInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *virtualhostbindInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&bind.Virtualhostbind{}, f.defaultInformer)
}

func (f *virtualhostbindInformer) Lister() internalversion.VirtualhostbindLister {
	return internalversion.NewVirtualhostbindLister(f.Informer().GetIndexer())
}
