//TODO copyright header

// This file was automatically generated by lister-gen

package v1alpha1

import (
	v1alpha1 "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/apis/backup/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// DefaultBackupLister helps list DefaultBackups.
type DefaultBackupLister interface {
	// List lists all DefaultBackups in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.DefaultBackup, err error)
	// DefaultBackups returns an object that can list and get DefaultBackups.
	DefaultBackups(namespace string) DefaultBackupNamespaceLister
	DefaultBackupListerExpansion
}

// defaultBackupLister implements the DefaultBackupLister interface.
type defaultBackupLister struct {
	indexer cache.Indexer
}

// NewDefaultBackupLister returns a new DefaultBackupLister.
func NewDefaultBackupLister(indexer cache.Indexer) DefaultBackupLister {
	return &defaultBackupLister{indexer: indexer}
}

// List lists all DefaultBackups in the indexer.
func (s *defaultBackupLister) List(selector labels.Selector) (ret []*v1alpha1.DefaultBackup, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.DefaultBackup))
	})
	return ret, err
}

// DefaultBackups returns an object that can list and get DefaultBackups.
func (s *defaultBackupLister) DefaultBackups(namespace string) DefaultBackupNamespaceLister {
	return defaultBackupNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// DefaultBackupNamespaceLister helps list and get DefaultBackups.
type DefaultBackupNamespaceLister interface {
	// List lists all DefaultBackups in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.DefaultBackup, err error)
	// Get retrieves the DefaultBackup from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.DefaultBackup, error)
	DefaultBackupNamespaceListerExpansion
}

// defaultBackupNamespaceLister implements the DefaultBackupNamespaceLister
// interface.
type defaultBackupNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all DefaultBackups in the indexer for a given namespace.
func (s defaultBackupNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.DefaultBackup, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.DefaultBackup))
	})
	return ret, err
}

// Get retrieves the DefaultBackup from the indexer for a given namespace and name.
func (s defaultBackupNamespaceLister) Get(name string) (*v1alpha1.DefaultBackup, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("defaultbackup"), name)
	}
	return obj.(*v1alpha1.DefaultBackup), nil
}
