//TODO copyright header

// This file was automatically generated by lister-gen

package v1alpha1

// DefaultBackupListerExpansion allows custom methods to be added to
// DefaultBackupLister.
type DefaultBackupListerExpansion interface{}

// DefaultBackupNamespaceListerExpansion allows custom methods to be added to
// DefaultBackupNamespaceLister.
type DefaultBackupNamespaceListerExpansion interface{}
