//TODO copyright header

// This file was automatically generated by informer-gen

package externalversions

import (
	"fmt"
	v1alpha1 "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/apis/backup/v1alpha1"
	bind_v1alpha1 "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/apis/bind/v1alpha1"
	deployment_v1alpha1 "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/apis/deployment/v1alpha1"
	lock_v1alpha1 "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/apis/lock/v1alpha1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=backup.servicefabrik.io, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithResource("defaultbackups"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Backup().V1alpha1().DefaultBackups().Informer()}, nil

		// Group=bind.servicefabrik.io, Version=v1alpha1
	case bind_v1alpha1.SchemeGroupVersion.WithResource("directorbinds"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Bind().V1alpha1().DirectorBinds().Informer()}, nil
	case bind_v1alpha1.SchemeGroupVersion.WithResource("dockerbinds"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Bind().V1alpha1().DockerBinds().Informer()}, nil

		// Group=deployment.servicefabrik.io, Version=v1alpha1
	case deployment_v1alpha1.SchemeGroupVersion.WithResource("directors"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Deployment().V1alpha1().Directors().Informer()}, nil
	case deployment_v1alpha1.SchemeGroupVersion.WithResource("dockers"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Deployment().V1alpha1().Dockers().Informer()}, nil

		// Group=lock.servicefabrik.io, Version=v1alpha1
	case lock_v1alpha1.SchemeGroupVersion.WithResource("deploymentlocks"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Lock().V1alpha1().DeploymentLocks().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
