// +build !ignore_autogenerated

//TODO copyright header

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	deployment "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/apis/deployment"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_Director_To_deployment_Director,
		Convert_deployment_Director_To_v1alpha1_Director,
		Convert_v1alpha1_DirectorList_To_deployment_DirectorList,
		Convert_deployment_DirectorList_To_v1alpha1_DirectorList,
		Convert_v1alpha1_DirectorSpec_To_deployment_DirectorSpec,
		Convert_deployment_DirectorSpec_To_v1alpha1_DirectorSpec,
		Convert_v1alpha1_DirectorStatus_To_deployment_DirectorStatus,
		Convert_deployment_DirectorStatus_To_v1alpha1_DirectorStatus,
		Convert_v1alpha1_DirectorStatusStrategy_To_deployment_DirectorStatusStrategy,
		Convert_deployment_DirectorStatusStrategy_To_v1alpha1_DirectorStatusStrategy,
		Convert_v1alpha1_DirectorStrategy_To_deployment_DirectorStrategy,
		Convert_deployment_DirectorStrategy_To_v1alpha1_DirectorStrategy,
	)
}

func autoConvert_v1alpha1_Director_To_deployment_Director(in *Director, out *deployment.Director, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_DirectorSpec_To_deployment_DirectorSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_DirectorStatus_To_deployment_DirectorStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Director_To_deployment_Director is an autogenerated conversion function.
func Convert_v1alpha1_Director_To_deployment_Director(in *Director, out *deployment.Director, s conversion.Scope) error {
	return autoConvert_v1alpha1_Director_To_deployment_Director(in, out, s)
}

func autoConvert_deployment_Director_To_v1alpha1_Director(in *deployment.Director, out *Director, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_deployment_DirectorSpec_To_v1alpha1_DirectorSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_deployment_DirectorStatus_To_v1alpha1_DirectorStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_deployment_Director_To_v1alpha1_Director is an autogenerated conversion function.
func Convert_deployment_Director_To_v1alpha1_Director(in *deployment.Director, out *Director, s conversion.Scope) error {
	return autoConvert_deployment_Director_To_v1alpha1_Director(in, out, s)
}

func autoConvert_v1alpha1_DirectorList_To_deployment_DirectorList(in *DirectorList, out *deployment.DirectorList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]deployment.Director)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_DirectorList_To_deployment_DirectorList is an autogenerated conversion function.
func Convert_v1alpha1_DirectorList_To_deployment_DirectorList(in *DirectorList, out *deployment.DirectorList, s conversion.Scope) error {
	return autoConvert_v1alpha1_DirectorList_To_deployment_DirectorList(in, out, s)
}

func autoConvert_deployment_DirectorList_To_v1alpha1_DirectorList(in *deployment.DirectorList, out *DirectorList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Director)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_deployment_DirectorList_To_v1alpha1_DirectorList is an autogenerated conversion function.
func Convert_deployment_DirectorList_To_v1alpha1_DirectorList(in *deployment.DirectorList, out *DirectorList, s conversion.Scope) error {
	return autoConvert_deployment_DirectorList_To_v1alpha1_DirectorList(in, out, s)
}

func autoConvert_v1alpha1_DirectorSpec_To_deployment_DirectorSpec(in *DirectorSpec, out *deployment.DirectorSpec, s conversion.Scope) error {
	out.Options = in.Options
	return nil
}

// Convert_v1alpha1_DirectorSpec_To_deployment_DirectorSpec is an autogenerated conversion function.
func Convert_v1alpha1_DirectorSpec_To_deployment_DirectorSpec(in *DirectorSpec, out *deployment.DirectorSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_DirectorSpec_To_deployment_DirectorSpec(in, out, s)
}

func autoConvert_deployment_DirectorSpec_To_v1alpha1_DirectorSpec(in *deployment.DirectorSpec, out *DirectorSpec, s conversion.Scope) error {
	out.Options = in.Options
	return nil
}

// Convert_deployment_DirectorSpec_To_v1alpha1_DirectorSpec is an autogenerated conversion function.
func Convert_deployment_DirectorSpec_To_v1alpha1_DirectorSpec(in *deployment.DirectorSpec, out *DirectorSpec, s conversion.Scope) error {
	return autoConvert_deployment_DirectorSpec_To_v1alpha1_DirectorSpec(in, out, s)
}

func autoConvert_v1alpha1_DirectorStatus_To_deployment_DirectorStatus(in *DirectorStatus, out *deployment.DirectorStatus, s conversion.Scope) error {
	out.State = in.State
	out.LastOperation = in.LastOperation
	out.Response = in.Response
	return nil
}

// Convert_v1alpha1_DirectorStatus_To_deployment_DirectorStatus is an autogenerated conversion function.
func Convert_v1alpha1_DirectorStatus_To_deployment_DirectorStatus(in *DirectorStatus, out *deployment.DirectorStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_DirectorStatus_To_deployment_DirectorStatus(in, out, s)
}

func autoConvert_deployment_DirectorStatus_To_v1alpha1_DirectorStatus(in *deployment.DirectorStatus, out *DirectorStatus, s conversion.Scope) error {
	out.State = in.State
	out.LastOperation = in.LastOperation
	out.Response = in.Response
	return nil
}

// Convert_deployment_DirectorStatus_To_v1alpha1_DirectorStatus is an autogenerated conversion function.
func Convert_deployment_DirectorStatus_To_v1alpha1_DirectorStatus(in *deployment.DirectorStatus, out *DirectorStatus, s conversion.Scope) error {
	return autoConvert_deployment_DirectorStatus_To_v1alpha1_DirectorStatus(in, out, s)
}

func autoConvert_v1alpha1_DirectorStatusStrategy_To_deployment_DirectorStatusStrategy(in *DirectorStatusStrategy, out *deployment.DirectorStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_DirectorStatusStrategy_To_deployment_DirectorStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_DirectorStatusStrategy_To_deployment_DirectorStatusStrategy(in *DirectorStatusStrategy, out *deployment.DirectorStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_DirectorStatusStrategy_To_deployment_DirectorStatusStrategy(in, out, s)
}

func autoConvert_deployment_DirectorStatusStrategy_To_v1alpha1_DirectorStatusStrategy(in *deployment.DirectorStatusStrategy, out *DirectorStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_deployment_DirectorStatusStrategy_To_v1alpha1_DirectorStatusStrategy is an autogenerated conversion function.
func Convert_deployment_DirectorStatusStrategy_To_v1alpha1_DirectorStatusStrategy(in *deployment.DirectorStatusStrategy, out *DirectorStatusStrategy, s conversion.Scope) error {
	return autoConvert_deployment_DirectorStatusStrategy_To_v1alpha1_DirectorStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_DirectorStrategy_To_deployment_DirectorStrategy(in *DirectorStrategy, out *deployment.DirectorStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_DirectorStrategy_To_deployment_DirectorStrategy is an autogenerated conversion function.
func Convert_v1alpha1_DirectorStrategy_To_deployment_DirectorStrategy(in *DirectorStrategy, out *deployment.DirectorStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_DirectorStrategy_To_deployment_DirectorStrategy(in, out, s)
}

func autoConvert_deployment_DirectorStrategy_To_v1alpha1_DirectorStrategy(in *deployment.DirectorStrategy, out *DirectorStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_deployment_DirectorStrategy_To_v1alpha1_DirectorStrategy is an autogenerated conversion function.
func Convert_deployment_DirectorStrategy_To_v1alpha1_DirectorStrategy(in *deployment.DirectorStrategy, out *DirectorStrategy, s conversion.Scope) error {
	return autoConvert_deployment_DirectorStrategy_To_v1alpha1_DirectorStrategy(in, out, s)
}
