//TODO copyright header

// This file was automatically generated by informer-gen

package v1alpha1

import (
	bind_v1alpha1 "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/apis/bind/v1alpha1"
	clientset "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/client/listers_generated/bind/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// DirectorBindInformer provides access to a shared informer and lister for
// DirectorBinds.
type DirectorBindInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DirectorBindLister
}

type directorBindInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDirectorBindInformer constructs a new informer for DirectorBind type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDirectorBindInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDirectorBindInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDirectorBindInformer constructs a new informer for DirectorBind type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDirectorBindInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BindV1alpha1().DirectorBinds(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BindV1alpha1().DirectorBinds(namespace).Watch(options)
			},
		},
		&bind_v1alpha1.DirectorBind{},
		resyncPeriod,
		indexers,
	)
}

func (f *directorBindInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDirectorBindInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *directorBindInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&bind_v1alpha1.DirectorBind{}, f.defaultInformer)
}

func (f *directorBindInformer) Lister() v1alpha1.DirectorBindLister {
	return v1alpha1.NewDirectorBindLister(f.Informer().GetIndexer())
}
