// +build !ignore_autogenerated

//TODO copyright header

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	lock "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/apis/lock"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_DeploymentLock_To_lock_DeploymentLock,
		Convert_lock_DeploymentLock_To_v1alpha1_DeploymentLock,
		Convert_v1alpha1_DeploymentLockList_To_lock_DeploymentLockList,
		Convert_lock_DeploymentLockList_To_v1alpha1_DeploymentLockList,
		Convert_v1alpha1_DeploymentLockSpec_To_lock_DeploymentLockSpec,
		Convert_lock_DeploymentLockSpec_To_v1alpha1_DeploymentLockSpec,
		Convert_v1alpha1_DeploymentLockStatus_To_lock_DeploymentLockStatus,
		Convert_lock_DeploymentLockStatus_To_v1alpha1_DeploymentLockStatus,
		Convert_v1alpha1_DeploymentLockStatusStrategy_To_lock_DeploymentLockStatusStrategy,
		Convert_lock_DeploymentLockStatusStrategy_To_v1alpha1_DeploymentLockStatusStrategy,
		Convert_v1alpha1_DeploymentLockStrategy_To_lock_DeploymentLockStrategy,
		Convert_lock_DeploymentLockStrategy_To_v1alpha1_DeploymentLockStrategy,
	)
}

func autoConvert_v1alpha1_DeploymentLock_To_lock_DeploymentLock(in *DeploymentLock, out *lock.DeploymentLock, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_DeploymentLockSpec_To_lock_DeploymentLockSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_DeploymentLockStatus_To_lock_DeploymentLockStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_DeploymentLock_To_lock_DeploymentLock is an autogenerated conversion function.
func Convert_v1alpha1_DeploymentLock_To_lock_DeploymentLock(in *DeploymentLock, out *lock.DeploymentLock, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeploymentLock_To_lock_DeploymentLock(in, out, s)
}

func autoConvert_lock_DeploymentLock_To_v1alpha1_DeploymentLock(in *lock.DeploymentLock, out *DeploymentLock, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_lock_DeploymentLockSpec_To_v1alpha1_DeploymentLockSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_lock_DeploymentLockStatus_To_v1alpha1_DeploymentLockStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_lock_DeploymentLock_To_v1alpha1_DeploymentLock is an autogenerated conversion function.
func Convert_lock_DeploymentLock_To_v1alpha1_DeploymentLock(in *lock.DeploymentLock, out *DeploymentLock, s conversion.Scope) error {
	return autoConvert_lock_DeploymentLock_To_v1alpha1_DeploymentLock(in, out, s)
}

func autoConvert_v1alpha1_DeploymentLockList_To_lock_DeploymentLockList(in *DeploymentLockList, out *lock.DeploymentLockList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]lock.DeploymentLock)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_DeploymentLockList_To_lock_DeploymentLockList is an autogenerated conversion function.
func Convert_v1alpha1_DeploymentLockList_To_lock_DeploymentLockList(in *DeploymentLockList, out *lock.DeploymentLockList, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeploymentLockList_To_lock_DeploymentLockList(in, out, s)
}

func autoConvert_lock_DeploymentLockList_To_v1alpha1_DeploymentLockList(in *lock.DeploymentLockList, out *DeploymentLockList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]DeploymentLock)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_lock_DeploymentLockList_To_v1alpha1_DeploymentLockList is an autogenerated conversion function.
func Convert_lock_DeploymentLockList_To_v1alpha1_DeploymentLockList(in *lock.DeploymentLockList, out *DeploymentLockList, s conversion.Scope) error {
	return autoConvert_lock_DeploymentLockList_To_v1alpha1_DeploymentLockList(in, out, s)
}

func autoConvert_v1alpha1_DeploymentLockSpec_To_lock_DeploymentLockSpec(in *DeploymentLockSpec, out *lock.DeploymentLockSpec, s conversion.Scope) error {
	out.Options = in.Options
	return nil
}

// Convert_v1alpha1_DeploymentLockSpec_To_lock_DeploymentLockSpec is an autogenerated conversion function.
func Convert_v1alpha1_DeploymentLockSpec_To_lock_DeploymentLockSpec(in *DeploymentLockSpec, out *lock.DeploymentLockSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeploymentLockSpec_To_lock_DeploymentLockSpec(in, out, s)
}

func autoConvert_lock_DeploymentLockSpec_To_v1alpha1_DeploymentLockSpec(in *lock.DeploymentLockSpec, out *DeploymentLockSpec, s conversion.Scope) error {
	out.Options = in.Options
	return nil
}

// Convert_lock_DeploymentLockSpec_To_v1alpha1_DeploymentLockSpec is an autogenerated conversion function.
func Convert_lock_DeploymentLockSpec_To_v1alpha1_DeploymentLockSpec(in *lock.DeploymentLockSpec, out *DeploymentLockSpec, s conversion.Scope) error {
	return autoConvert_lock_DeploymentLockSpec_To_v1alpha1_DeploymentLockSpec(in, out, s)
}

func autoConvert_v1alpha1_DeploymentLockStatus_To_lock_DeploymentLockStatus(in *DeploymentLockStatus, out *lock.DeploymentLockStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_DeploymentLockStatus_To_lock_DeploymentLockStatus is an autogenerated conversion function.
func Convert_v1alpha1_DeploymentLockStatus_To_lock_DeploymentLockStatus(in *DeploymentLockStatus, out *lock.DeploymentLockStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeploymentLockStatus_To_lock_DeploymentLockStatus(in, out, s)
}

func autoConvert_lock_DeploymentLockStatus_To_v1alpha1_DeploymentLockStatus(in *lock.DeploymentLockStatus, out *DeploymentLockStatus, s conversion.Scope) error {
	return nil
}

// Convert_lock_DeploymentLockStatus_To_v1alpha1_DeploymentLockStatus is an autogenerated conversion function.
func Convert_lock_DeploymentLockStatus_To_v1alpha1_DeploymentLockStatus(in *lock.DeploymentLockStatus, out *DeploymentLockStatus, s conversion.Scope) error {
	return autoConvert_lock_DeploymentLockStatus_To_v1alpha1_DeploymentLockStatus(in, out, s)
}

func autoConvert_v1alpha1_DeploymentLockStatusStrategy_To_lock_DeploymentLockStatusStrategy(in *DeploymentLockStatusStrategy, out *lock.DeploymentLockStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_DeploymentLockStatusStrategy_To_lock_DeploymentLockStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_DeploymentLockStatusStrategy_To_lock_DeploymentLockStatusStrategy(in *DeploymentLockStatusStrategy, out *lock.DeploymentLockStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeploymentLockStatusStrategy_To_lock_DeploymentLockStatusStrategy(in, out, s)
}

func autoConvert_lock_DeploymentLockStatusStrategy_To_v1alpha1_DeploymentLockStatusStrategy(in *lock.DeploymentLockStatusStrategy, out *DeploymentLockStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_lock_DeploymentLockStatusStrategy_To_v1alpha1_DeploymentLockStatusStrategy is an autogenerated conversion function.
func Convert_lock_DeploymentLockStatusStrategy_To_v1alpha1_DeploymentLockStatusStrategy(in *lock.DeploymentLockStatusStrategy, out *DeploymentLockStatusStrategy, s conversion.Scope) error {
	return autoConvert_lock_DeploymentLockStatusStrategy_To_v1alpha1_DeploymentLockStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_DeploymentLockStrategy_To_lock_DeploymentLockStrategy(in *DeploymentLockStrategy, out *lock.DeploymentLockStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_DeploymentLockStrategy_To_lock_DeploymentLockStrategy is an autogenerated conversion function.
func Convert_v1alpha1_DeploymentLockStrategy_To_lock_DeploymentLockStrategy(in *DeploymentLockStrategy, out *lock.DeploymentLockStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeploymentLockStrategy_To_lock_DeploymentLockStrategy(in, out, s)
}

func autoConvert_lock_DeploymentLockStrategy_To_v1alpha1_DeploymentLockStrategy(in *lock.DeploymentLockStrategy, out *DeploymentLockStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_lock_DeploymentLockStrategy_To_v1alpha1_DeploymentLockStrategy is an autogenerated conversion function.
func Convert_lock_DeploymentLockStrategy_To_v1alpha1_DeploymentLockStrategy(in *lock.DeploymentLockStrategy, out *DeploymentLockStrategy, s conversion.Scope) error {
	return autoConvert_lock_DeploymentLockStrategy_To_v1alpha1_DeploymentLockStrategy(in, out, s)
}
