//TODO copyright header

// This file was automatically generated by lister-gen

package internalversion

// DeploymentLockListerExpansion allows custom methods to be added to
// DeploymentLockLister.
type DeploymentLockListerExpansion interface{}

// DeploymentLockNamespaceListerExpansion allows custom methods to be added to
// DeploymentLockNamespaceLister.
type DeploymentLockNamespaceListerExpansion interface{}
