/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by apiregister-gen. Do not edit it manually!

package lock

import (
	"fmt"
	"github.com/kubernetes-incubator/apiserver-builder/pkg/builders"
	"k8s.io/apimachinery/pkg/apis/meta/internalversion"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apiserver/pkg/endpoints/request"
	"k8s.io/apiserver/pkg/registry/rest"
)

var (
	InternalDeploymentLock = builders.NewInternalResource(
		"deploymentlocks",
		"DeploymentLock",
		func() runtime.Object { return &DeploymentLock{} },
		func() runtime.Object { return &DeploymentLockList{} },
	)
	InternalDeploymentLockStatus = builders.NewInternalResourceStatus(
		"deploymentlocks",
		"DeploymentLockStatus",
		func() runtime.Object { return &DeploymentLock{} },
		func() runtime.Object { return &DeploymentLockList{} },
	)
	// Registered resources and subresources
	ApiVersion = builders.NewApiGroup("lock.servicefabrik.io").WithKinds(
		InternalDeploymentLock,
		InternalDeploymentLockStatus,
	)

	// Required by code generated by go2idl
	AddToScheme        = ApiVersion.SchemaBuilder.AddToScheme
	SchemeBuilder      = ApiVersion.SchemaBuilder
	localSchemeBuilder = &SchemeBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

// +genclient
// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type DeploymentLock struct {
	metav1.TypeMeta
	metav1.ObjectMeta
	Spec   DeploymentLockSpec
	Status DeploymentLockStatus
}

type DeploymentLockSpec struct {
	Options string
}

type DeploymentLockStatus struct {
}

//
// DeploymentLock Functions and Structs
//
// +k8s:deepcopy-gen=false
type DeploymentLockStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type DeploymentLockStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type DeploymentLockList struct {
	metav1.TypeMeta
	metav1.ListMeta
	Items []DeploymentLock
}

func (DeploymentLock) NewStatus() interface{} {
	return DeploymentLockStatus{}
}

func (pc *DeploymentLock) GetStatus() interface{} {
	return pc.Status
}

func (pc *DeploymentLock) SetStatus(s interface{}) {
	pc.Status = s.(DeploymentLockStatus)
}

func (pc *DeploymentLock) GetSpec() interface{} {
	return pc.Spec
}

func (pc *DeploymentLock) SetSpec(s interface{}) {
	pc.Spec = s.(DeploymentLockSpec)
}

func (pc *DeploymentLock) GetObjectMeta() *metav1.ObjectMeta {
	return &pc.ObjectMeta
}

func (pc *DeploymentLock) SetGeneration(generation int64) {
	pc.ObjectMeta.Generation = generation
}

func (pc DeploymentLock) GetGeneration() int64 {
	return pc.ObjectMeta.Generation
}

// Registry is an interface for things that know how to store DeploymentLock.
// +k8s:deepcopy-gen=false
type DeploymentLockRegistry interface {
	ListDeploymentLocks(ctx request.Context, options *internalversion.ListOptions) (*DeploymentLockList, error)
	GetDeploymentLock(ctx request.Context, id string, options *metav1.GetOptions) (*DeploymentLock, error)
	CreateDeploymentLock(ctx request.Context, id *DeploymentLock) (*DeploymentLock, error)
	UpdateDeploymentLock(ctx request.Context, id *DeploymentLock) (*DeploymentLock, error)
	DeleteDeploymentLock(ctx request.Context, id string) (bool, error)
}

// NewRegistry returns a new Registry interface for the given Storage. Any mismatched types will panic.
func NewDeploymentLockRegistry(sp builders.StandardStorageProvider) DeploymentLockRegistry {
	return &storageDeploymentLock{sp}
}

// Implement Registry
// storage puts strong typing around storage calls
// +k8s:deepcopy-gen=false
type storageDeploymentLock struct {
	builders.StandardStorageProvider
}

func (s *storageDeploymentLock) ListDeploymentLocks(ctx request.Context, options *internalversion.ListOptions) (*DeploymentLockList, error) {
	if options != nil && options.FieldSelector != nil && !options.FieldSelector.Empty() {
		return nil, fmt.Errorf("field selector not supported yet")
	}
	st := s.GetStandardStorage()
	obj, err := st.List(ctx, options)
	if err != nil {
		return nil, err
	}
	return obj.(*DeploymentLockList), err
}

func (s *storageDeploymentLock) GetDeploymentLock(ctx request.Context, id string, options *metav1.GetOptions) (*DeploymentLock, error) {
	st := s.GetStandardStorage()
	obj, err := st.Get(ctx, id, options)
	if err != nil {
		return nil, err
	}
	return obj.(*DeploymentLock), nil
}

func (s *storageDeploymentLock) CreateDeploymentLock(ctx request.Context, object *DeploymentLock) (*DeploymentLock, error) {
	st := s.GetStandardStorage()
	obj, err := st.Create(ctx, object, nil, true)
	if err != nil {
		return nil, err
	}
	return obj.(*DeploymentLock), nil
}

func (s *storageDeploymentLock) UpdateDeploymentLock(ctx request.Context, object *DeploymentLock) (*DeploymentLock, error) {
	st := s.GetStandardStorage()
	obj, _, err := st.Update(ctx, object.Name, rest.DefaultUpdatedObjectInfo(object), nil, nil)
	if err != nil {
		return nil, err
	}
	return obj.(*DeploymentLock), nil
}

func (s *storageDeploymentLock) DeleteDeploymentLock(ctx request.Context, id string) (bool, error) {
	st := s.GetStandardStorage()
	_, sync, err := st.Delete(ctx, id, nil)
	return sync, err
}
