//TODO copyright header

// This file was automatically generated by informer-gen

package v1alpha1

import (
	lock_v1alpha1 "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/apis/lock/v1alpha1"
	clientset "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/client/listers_generated/lock/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// DeploymentLockInformer provides access to a shared informer and lister for
// DeploymentLocks.
type DeploymentLockInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DeploymentLockLister
}

type deploymentLockInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDeploymentLockInformer constructs a new informer for DeploymentLock type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDeploymentLockInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDeploymentLockInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDeploymentLockInformer constructs a new informer for DeploymentLock type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDeploymentLockInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LockV1alpha1().DeploymentLocks(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LockV1alpha1().DeploymentLocks(namespace).Watch(options)
			},
		},
		&lock_v1alpha1.DeploymentLock{},
		resyncPeriod,
		indexers,
	)
}

func (f *deploymentLockInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDeploymentLockInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *deploymentLockInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&lock_v1alpha1.DeploymentLock{}, f.defaultInformer)
}

func (f *deploymentLockInformer) Lister() v1alpha1.DeploymentLockLister {
	return v1alpha1.NewDeploymentLockLister(f.Informer().GetIndexer())
}
