#!/bin/bash -x

set_kubeconfig() {
  set +x
  apiserver_ip=$(bosh int templates/apiserver.yml --path /instance_groups/0/jobs/0/properties/ip)
  apiserver_port=$(bosh int templates/apiserver.yml --path /instance_groups/0/jobs/0/properties/port)
  apiserver="https://${apiserver_ip}:${apiserver_port}"

  tmp_ca_file="$(mktemp)"
  trap 'rm "${tmp_ca_file}"' EXIT

  bosh int templates/vars-store.yml --path /tls_etcd/ca > "${tmp_ca_file}"
  admin_password="admin"

  cluster_name="apiserver"
  user_name="${cluster_name}/admin"
  context_name="${cluster_name}"

  kubectl config set-cluster "${cluster_name}" --server="${apiserver}" --certificate-authority="${tmp_ca_file}" --embed-certs=true
  kubectl config set-credentials "${user_name}" --token="${admin_password}"
  kubectl config set-context "${context_name}" --cluster="${cluster_name}" --user="${user_name}"
  kubectl config use-context "${context_name}"

  echo "Created new kubectl context ${context_name}"
}
set_kubeconfig
