//TODO copyright header

// This file was automatically generated by lister-gen

package v1alpha1

// DirectorBindListerExpansion allows custom methods to be added to
// DirectorBindLister.
type DirectorBindListerExpansion interface{}

// DirectorBindNamespaceListerExpansion allows custom methods to be added to
// DirectorBindNamespaceLister.
type DirectorBindNamespaceListerExpansion interface{}

// DockerBindListerExpansion allows custom methods to be added to
// DockerBindLister.
type DockerBindListerExpansion interface{}

// DockerBindNamespaceListerExpansion allows custom methods to be added to
// DockerBindNamespaceLister.
type DockerBindNamespaceListerExpansion interface{}
