//TODO copyright header

// This file was automatically generated by lister-gen

package internalversion

// DirectorListerExpansion allows custom methods to be added to
// DirectorLister.
type DirectorListerExpansion interface{}

// DirectorNamespaceListerExpansion allows custom methods to be added to
// DirectorNamespaceLister.
type DirectorNamespaceListerExpansion interface{}

// DockerListerExpansion allows custom methods to be added to
// DockerLister.
type DockerListerExpansion interface{}

// DockerNamespaceListerExpansion allows custom methods to be added to
// DockerNamespaceLister.
type DockerNamespaceListerExpansion interface{}
